//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class poblacion
    {
        public poblacion()
        {
            this.nino = new HashSet<nino>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<nino> nino { get; set; }
    }
}
