//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tanda
    {
        public tanda()
        {
            this.inscripciones_tanda_casa = new HashSet<inscripciones_tanda_casa>();
            this.monitor_tanda_casa = new HashSet<monitor_tanda_casa>();
            this.monitor_tareas_tandas = new HashSet<monitor_tareas_tandas>();
        }
    
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual ICollection<inscripciones_tanda_casa> inscripciones_tanda_casa { get; set; }
        public virtual ICollection<monitor_tanda_casa> monitor_tanda_casa { get; set; }
        public virtual ICollection<monitor_tareas_tandas> monitor_tareas_tandas { get; set; }
    }
}
