//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad_casa
    {
        public string codigo_actividad { get; set; }
        public string codigo_casa { get; set; }
        public int nivel_calidad { get; set; }
    
        public virtual actividad actividad { get; set; }
        public virtual casa casa { get; set; }
    }
}
