//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public administrador()
        {
            this.administra_casa = new HashSet<administra_casa>();
        }
    
        public string DNI { get; set; }
        public int num_SS { get; set; }
        public string titulacion { get; set; }
    
        public virtual ICollection<administra_casa> administra_casa { get; set; }
        public virtual personal personal { get; set; }
    }
}
