//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class casa
    {
        public casa()
        {
            this.actividad_casa = new HashSet<actividad_casa>();
            this.administra_casa = new HashSet<administra_casa>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public bool litoral { get; set; }
        public string codigo_comarca { get; set; }
    
        public virtual ICollection<actividad_casa> actividad_casa { get; set; }
        public virtual ICollection<administra_casa> administra_casa { get; set; }
    }
}
