//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripciones_tanda_casa
    {
        public int carnet_niño { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public string nombre_casa { get; set; }
        public int numero_inscripcion { get; set; }
    
        public virtual nino nino { get; set; }
        public virtual tanda tanda { get; set; }
    }
}
