//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor
    {
        public monitor()
        {
            this.monitor_tanda_casa = new HashSet<monitor_tanda_casa>();
            this.monitor_tareas_tandas = new HashSet<monitor_tareas_tandas>();
        }
    
        public string DNI { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    
        public virtual personal personal { get; set; }
        public virtual ICollection<monitor_tanda_casa> monitor_tanda_casa { get; set; }
        public virtual ICollection<monitor_tareas_tandas> monitor_tareas_tandas { get; set; }
    }
}
